#!/bin/bash
# Run the deployment image as a webserver for api calls

# Run detached for debugging
#docker run --rm --name server-pricing-model -p 80:80 -p 443:443 server-pricing-model:latest
docker run --rm -d --name server-pricing-model -p 80:80 -p 443:443 server-pricing-model:latest
